server:
  port: 9527
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /api/v1
spring:
  profiles:
    active: wzmtr
  messages:
    basename: i18n/messages
  application:
    name: alarm-center
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      enabled: true
swagger:
    enable: true
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
      limit: 100
#  jackson:
#    time-zone: GMT+8

