spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  jackson:
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: true

  # dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.20.10.187:3306/alarm_center?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      read-only: false
      connection-timeout: 60000
      idle-timeout: 50000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      maximum-pool-size: 100
      minimum-idle: 10

  rabbitmq:
    addresses: 10.20.10.187:5672, 10.20.10.188:5672
    username: yly
    password: 123456
    virtual-host: wzmtr
#    virtual-host: test

  #redis
  redis:
    cluster:
      nodes: 10.20.10.187:7001, 10.20.10.187:7002, 10.20.10.188:7001, 10.20.10.188:7002
    jedis:
      pool:
        max-active: 50
        min-idle: 0
        max-idle: 50
        max-wait: -1
    key-prefix: dev-
#    key-prefix: test-


#kafka-monitor:
#  port: "udp:localhost/10086"
#  topic: myTopic
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.zte.msg.alarmcenter.entity
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    multiple-result-sets-enabled: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    map-underscore-to-camel-case: true
  global-config:
    sql-parser-cache: true
    db-config:
      logic-delete-field: is_deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
sign:
  verify: true

async:
  push:
   pool-size:
     core: 100
     max: 100
logging:
  file:
    path: ./log

fdfs:
  connect-timeout: 600
  so-timeout: 2500
  thumb-image:
    height: 60
    width: 60
  pool:
    max-total: 300
    max-total-per-key: 300
    max-wait-millis: 5000
  tracker-list:
    - 10.20.10.187:22122
    - 10.20.10.188:22122
redisson:
  address: redis://10.20.10.187:6379
  password: Zxwz123!@#

imagePath: "http://10.20.10.187:8888/"